// <auto-generated />
using System;
using MaMiKrCh.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MaMiKrCh.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20191030194156_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MaMiKrCh.Models.ProductModel.MarketingMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int?>("ProductId");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("MarketingMaterials");

                    b.HasDiscriminator<string>("Discriminator").HasValue("MarketingMaterial");
                });

            modelBuilder.Entity("MaMiKrCh.Models.ProductModel.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("SalesPitch");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MaMiKrCh.Models.ProductModel.MarketingText", b =>
                {
                    b.HasBaseType("MaMiKrCh.Models.ProductModel.MarketingMaterial");

                    b.Property<string>("Text");

                    b.HasDiscriminator().HasValue("MarketingText");
                });

            modelBuilder.Entity("MaMiKrCh.Models.ProductModel.MarketingMaterial", b =>
                {
                    b.HasOne("MaMiKrCh.Models.ProductModel.Product")
                        .WithMany("MarketingMaterials")
                        .HasForeignKey("ProductId");
                });
#pragma warning restore 612, 618
        }
    }
}
