// <auto-generated />
using System;
using MaMiKrCh_API.EFContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MaMiKrCh_API.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20191210095355_initela")]
    partial class initela
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MaMiKrCh_API.Models.ProductModel.MarketingMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("MarketingMaterials");

                    b.HasDiscriminator<string>("Discriminator").HasValue("MarketingMaterial");
                });

            modelBuilder.Entity("MaMiKrCh_API.Models.ProductModel.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesPitch")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MaMiKrCh_API.Models.ProductModel.MarketingText", b =>
                {
                    b.HasBaseType("MaMiKrCh_API.Models.ProductModel.MarketingMaterial");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("MarketingText");
                });

            modelBuilder.Entity("MaMiKrCh_API.Models.ProductModel.MarketingMaterial", b =>
                {
                    b.HasOne("MaMiKrCh_API.Models.ProductModel.Product", "Product")
                        .WithMany("MarketingMaterials")
                        .HasForeignKey("ProductId");
                });
#pragma warning restore 612, 618
        }
    }
}
